### ISSUE TITLE
intense-images is not so good on mobile phone browsers

### ISSUE THREAD

**Issue by LGD-Fr** [cccroix/cccroix.github.io#13]

**Comment by lucarabistouille** [comment]
It hasn't been built for mobile phone, however the official demo works fine on my android with fennec (firefox) : [demo](http://tholman.com/intense-images/)

**Comment by lucarabistouille** [comment]
Seems to be corrected with commit 0998b3825cd7d92b0af2a6c71dea8f92924081ef 

```
Shows resized pictures on "eglises" pages

    and shows hd picture with the intense-images viewer
```

**Comment by LGD-Fr** [comment]
no, corrected with db65ddd

**Comment by luc--** [comment]
That seemed to be already working ^^

**Comment by LGD-Fr** [comment]
@luc-- You don’t seem to understand…
