### ISSUE TITLE
improve the "add post" link

### ISSUE THREAD

**Issue by LGD-Fr** [cccroix/cccroix.github.io#7]
with JS to give the good date/time to the GitHub editor.

**Comment by lucarabistouille** [comment]
With a form as you said on IRC !

**Comment by LGD-Fr** [comment]
With ef7eda3 and 6a40b1c the date is automatically set.

**Comment by LGD-Fr** [comment]
I’m not sure the form is necessary.

**Comment by lucarabistouille** [comment]
Yes, Github is enough good.
