### ISSUE TITLE
Images for each article

### ISSUE THREAD

**Issue by lucarabistouille** [cccroix/cccroix.github.io#9]
Because the landing page is a bit austere... (I'll work on it with the scss in the « css » branch)

**Comment by LGD-Fr** [comment]
Good luck ;-)

**Comment by lucarabistouille** [comment]
Yep !

**Comment by lucarabistouille** [comment]
Done for the churches on  b5e32c9

**Comment by lucarabistouille** [comment]
Issue  **host on the repo all pictures #15** must be resolved before.

**Comment by LGD-Fr** [comment]
with a filename on the front-matter I suppose

**Comment by lucarabistouille** [comment]
That was what I thought. I can do it either !

**Comment by lucarabistouille** [comment]
We leave the idea of an image near the title, that's better I think.

However --> interessant idea : [figures & légendes](http://www.w3.org/Style/Examples/007/figures)

**Comment by lucarabistouille** [comment]
On peut faire simplement du 

``` css
img + p {
    ...
}
```

si on veut éviter l'utilisation d'une nouvelle classe **figure** (le style ne porte alors que sur les `<p>` qui suivent `<img>`).
